CREATE TABLE T_QF_MARCA(
ID_MARCA INTEGER PRIMARY KEY,
DS_MARCA VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE T_QF_CATEGORIA (
ID_CATEGORIA INTEGER PRIMARY KEY,
DS_CATEGORIA VARCHAR2(1500) NOT NULL UNIQUE
);

CREATE TABLE T_QF_CLIENTE (
ID_CLIENTE INTEGER PRIMARY KEY,
NM_CLIENTE VARCHAR2(60) NOT NULL,
CPF VARCHAR2(15) NOT NULL UNIQUE,
DT_NASCIMENTO DATE,
SX_CLIENTE VARCHAR2(2) NOT NULL,
ST_CLIENTE VARCHAR2(1) NOT NULL
);

CREATE TABLE T_QF_ARMAZEM (
ID_ARMAZEM INTEGER PRIMARY KEY,
DS_ARMAZEM VARCHAR2(100) NOT NULL UNIQUE,
LOCAL_ARMAZEM VARCHAR2(100) NOT NULL
);

CREATE TABLE T_QF_CUPOM (
ID_CUPOM INTEGER PRIMARY KEY,
CD_CUPOM VARCHAR2(100) NOT NULL,
VL_DESCONTO NUMBER(5,2) NOT NULL,
VAL_CUPOM DATE
);

CREATE TABLE T_QF_ENDERECO (
ID_ENDERECO INTEGER PRIMARY KEY,
ID_CLIENTE INTEGER,
CEP VARCHAR2(15) NOT NULL,
LOGRADOURO VARCHAR2(15) NOT NULL,
NUMERO NUMBER NOT NULL,
COMPLEMENTO VARCHAR2(150),
BAIRRO VARCHAR2(150) NOT NULL,
CIDADE VARCHAR2(150) NOT NULL,
UF VARCHAR2(2) NOT NULL,
PONTO_REFERENCIA VARCHAR2(150),
FOREIGN KEY (ID_CLIENTE) REFERENCES T_QF_CLIENTE (ID_CLIENTE)
);

CREATE TABLE T_QF_AUTENTICA (
ID_AUTENTICA INTEGER PRIMARY KEY,
ID_CLIENTE INTEGER,
LOGIN VARCHAR2(256) NOT NULL UNIQUE,
SENHA VARCHAR2(30) NOT NULL,
FOREIGN KEY (ID_CLIENTE) REFERENCES T_QF_CLIENTE(ID_CLIENTE)
);
 
CREATE TABLE T_QF_PRODUTO (
ID_PRODUTO INTEGER PRIMARY KEY,
ID_CATEGORIA INTEGER,
ID_MARCA INTEGER,
DS_PRODUTO VARCHAR2(150) NOT NULL,
VL_PRODUTO NUMBER(5,2) NOT NULL,
PESO NUMBER(5,2) NOT NULL,
DIMENSOES VARCHAR2(20) NOT NULL,
FOREIGN KEY (ID_CATEGORIA) REFERENCES T_QF_CATEGORIA(ID_CATEGORIA),
FOREIGN KEY (ID_MARCA) REFERENCES T_QF_MARCA(ID_MARCA)
);

CREATE TABLE T_QF_PEDIDO (
ID_PEDIDO INTEGER PRIMARY KEY,
ID_CLIENTE INTEGER,
ID_CUPOM INTEGER,
DT_HR_PEDIDO DATE NOT NULL,
ST_PEDIDO VARCHAR2(20) NOT NULL,
VL_TOTAL NUMBER(5,2) NOT NULL,
VL_DESCONTO NUMBER(5,2) NOT NULL,
OBS_GERAIS VARCHAR2(255),
FOREIGN KEY (ID_CLIENTE) REFERENCES T_QF_CLIENTE(ID_CLIENTE),
FOREIGN KEY (ID_CUPOM) REFERENCES T_QF_CUPOM(ID_CUPOM)
);

CREATE TABLE T_QF_ITEM_PEDIDO (
ID_ITEM INTEGER,
ID_PRODUTO INTEGER,
ID_PEDIDO INTEGER,
QT_PRODUTO INTEGER NOT NULL,
VL_TOTAL NUMBER(5,2) NOT NULL,
VL_CUPOM NUMBER(5,2),
CONSTRAINT PEDIDOITEM PRIMARY KEY(ID_PEDIDO,ID_ITEM),
CONSTRAINT PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES T_QF_PEDIDO(ID_PEDIDO)
);

CREATE TABLE T_QF_PAGAMENTO (
ID_PAGAMENTO INTEGER PRIMARY KEY,
ID_PEDIDO INTEGER,
FORMA_PAGAMENTO VARCHAR2(50) NOT NULL,
VL_PAGAMENTO NUMBER(5,2) NOT NULL,
DT_HORA_PAGAMENTO DATE NOT NULL,
ST_PAGAMENTO VARCHAR2(20) NOT NULL,
FOREIGN KEY (ID_PEDIDO) REFERENCES T_QF_PEDIDO(ID_PEDIDO)
);

CREATE TABLE T_QF_ESTOQUE (
ID_ESTOQUE INTEGER PRIMARY KEY,
ID_PRODUTO INTEGER,
ID_ARMAZEM INTEGER,
QTD_DISPONIVEL INTEGER NOT NULL,
FOREIGN KEY (ID_PRODUTO) REFERENCES T_QF_PRODUTO(ID_PRODUTO),
FOREIGN KEY (ID_ARMAZEM) REFERENCES T_QF_ARMAZEM(ID_ARMAZEM)
);

ALTER TABLE T_QF_ESTOQUE ADD DT_HR_ESTOQUE DATE;
ALTER TABLE T_QF_PRODUTO ADD COR_PRODUTO VARCHAR(20);

DROP TABLE T_QF_ESTOQUE;
DROP TABLE T_QF_PAGAMENTO;
DROP TABLE T_QF_ITEM_PEDIDO;
DROP TABLE T_QF_PEDIDO;
DROP TABLE T_QF_PRODUTO;
DROP TABLE T_QF_AUTENTICA;
DROP TABLE T_QF_ENDERECO;
DROP TABLE T_QF_CUPOM;
DROP TABLE T_QF_ARMAZEM;
DROP TABLE T_QF_CLIENTE;
DROP TABLE T_QF_CATEGORIA;
DROP TABLE T_QF_MARCA;