CREATE TABLE T_UNV_ALUNO (
ID_ALUNO INTEGER PRIMARY KEY,
NM_ALUNO VARCHAR2(100) NOT NULL,
DT_NASCIMENTO DATE,
CPF NUMBER(11) NOT NULL,
SEXO CHAR(1)
);

CREATE TABLE T_UNV_CURSO (
ID_CURSO INTEGER PRIMARY KEY,
NM_CURSO VARCHAR2(100)
);

CREATE TABLE T_UNV_PROFESSOR (
ID_PROFESSOR INTEGER PRIMARY KEY,
NM_PROFESSOR VARCHAR2(100) NOT NULL
);

CREATE TABLE T_UNV_TURMA (
ID_TURMA INTEGER PRIMARY KEY,
ID_CURSO INTEGER,
DATA_CRIACAO DATE NOT NULL,
NM_TURMA VARCHAR2(100) NOT NULL,
SITUACAO CHAR,
FOREIGN KEY (ID_CURSO) REFERENCES T_UNV_CURSO (ID_CURSO)
);

CREATE TABLE T_UNV_DISCIPLINA (
ID_DISCIPLINA INTEGER PRIMARY KEY,
ID_CURSO INTEGER,
NM_DISCIPLINA VARCHAR2(155) NOT NULL,
EMENTA VARCHAR2(155),
REF_BIBLIOGRAFICO VARCHAR2(155) NOT NULL,
METODOLOGIA VARCHAR2(155) NOT NULL,
CARGA_HORARIA INTEGER,
MODALIDADE VARCHAR2(155),
FOREIGN KEY (ID_CURSO) REFERENCES T_UNV_CURSO (ID_CURSO)
);

CREATE TABLE T_UNV_PROFESSOR_DISCIPLINA (
ID_PROFESSOR_DISCIPLINA INTEGER PRIMARY KEY,
ID_DISCIPLINA INTEGER,
ID_PROFESSOR INTEGER,
FOREIGN KEY (ID_DISCIPLINA) REFERENCES T_UNV_DISCIPLINA (ID_DISCIPLINA),
FOREIGN KEY (ID_PROFESSOR) REFERENCES T_UNV_PROFESSOR (ID_PROFESSOR)
);

CREATE TABLE T_UNV_PROFESSOR_TURMA (
ID_TURMA_PROFESSOR INTEGER PRIMARY KEY,
ID_PROFESSOR INTEGER,
ID_TURMA INTEGER,
FOREIGN KEY (ID_PROFESSOR) REFERENCES T_UNV_PROFESSOR (ID_PROFESSOR),
FOREIGN KEY (ID_TURMA) REFERENCES T_UNV_TURMA (ID_TURMA)
);

CREATE TABLE T_UNV_ALUNO_TURMA (
ID_ALUNO INTEGER,
ID_TURMA INTEGER,
PRIMARY KEY (ID_ALUNO),
FOREIGN KEY (ID_ALUNO) REFERENCES T_UNV_ALUNO(ID_ALUNO),
FOREIGN KEY (ID_TURMA) REFERENCES T_UNV_TURMA(ID_TURMA)
);

ALTER TABLE T_UNV_ALUNO ADD SITUACAO CHAR(1);
ALTER TABLE T_UNV_PROFESSOR ADD SITUACAO CHAR(1);
ALTER TABLE T_UNV_DISCIPLINA RENAME COLUMN CARGA_HORARIO TO CARGA_HORARIA;
ALTER TABLE T_UNV_DISCIPLINA RENAME COLUMN CARGA_HORARIA TO CH;
ALTER TABLE T_UNV_ALUNO RENAME TO DISCENTE;
ALTER TABLE T_UNV_PROFESSOR RENAME TO DOCENTE;
ALTER TABLE T_UNV_DISCIPLINA MODIFY (EMENTA, REF_BIBLIOGRAFICA, METODOLOGIA) LONG VARCHAR;
ALTER TABLE DISCENTE MODIFY CPF UNIQUE;
ALTER TABLE T_UNV_CURSO MODIFY NM_CURSO UNIQUE;
ALTER TABLE T_UNV_TURMA MODIFY NM_TURMA UNIQUE;
ALTER TABLE DISCENTE MODIFY SEXO CHAR(1) ADD CONSTRAINT CHK_SEXO CHECK (SEXO IN ('I', 'F', 'M'));
ALTER TABLE T_UNV_DISCIPLINA MODIFY MODALIDADE VARCHAR2(155) ADD CONSTRAINT CHK_MOD CHECK(MODALIDADE IN('PRESENCIAL','REMOTO'));
ALTER TABLE T_UNV_TURMA MODIFY SITUACAO CHAR ADD CONSTRAINT CHK_SIT CHECK(SITUACAO IN('I','A'));
DROP T_UNV_ALUNO_TURMA;
DROP T_UNV_PROFESSOR_TURMA;
DROP T_UNV_PROFESSOR_DISCIPLINA;
DROP T_UNV_DISCIPLINA;
DROP T_UNV_TURMA;
DROP T_UNV_PROFESSOR;
DROP T_UNV_CURSO;
DROP T_UNV_ALUNO;
